version: "3"
networks:
  msanetwork:
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16

services: 

  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 123456
    ports: 
      - 5432:5432
    networks:
      msanetwork:
        ipv4_address: 172.18.0.2

  rabbit:
    image: rabbitmq:3.12-management
    ports: 
      - 5672:5672
      - 15672:15672 
    networks:
      msanetwork:
        ipv4_address: 172.18.0.3

  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      MSSQL_SA_PASSWORD: myPassw0rd2o19
      ACCEPT_EULA: Y
    ports:
      - 1433:1433
    networks:
      msanetwork:
        ipv4_address: 172.18.0.4      

  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
      msanetwork:
        ipv4_address: 172.18.0.5    

  discountms:
    image: discountms
    ports:
      - 5085:80
    networks:
      msanetwork:
        ipv4_address: 172.18.0.6

  userms:
    image: userms
    ports:
      - 5246:80
    networks:
      msanetwork:
        ipv4_address: 172.18.0.7        



